spring:
  # 发送邮件配置
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 1244910580@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: ncuqxbrqxliahchf # 配置申请到的授权码(刚让复制的授权码)
#    host: mail.asiainfo.com # 配置 smtp 服务器地址
#    port: 587 # smtp 服务器的端口
#    username: dinggang@asiainfo.com # 配置邮箱用户名(你的邮箱地址)
#    password: slyWOAINI1314 # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
#        debug: true
    from: 1244910580@qq.com # 发送方邮件，在yml中可方便更改
logging:
  level:
    root: INFO
server:
  port: 8081